version: "3.7"
#docker network create shopspiker-network

volumes:
  elasticsearch:
  
networks:
  shopspiker-network:
    external: true

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - shopspiker-network
    ports:
      - "6379:6379"



  